name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "**/*.md"
      - "LICENSE"
      - "src/Server/**"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "**/*.md"
      - "LICENSE"
      - "src/Server/**"
      - ".gitignore"
  workflow_dispatch:

jobs:
  rust:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src/Build

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build Rust
        run: .\appBuild.bat

      - name: Upload Rust EXE
        uses: actions/upload-artifact@v4
        with:
          name: RustConnectApp
          path: src/Build/RustConnect.exe

  go:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src/Build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Go server
        run: .\serverBuild.bat

      - name: Upload Server
        uses: actions/upload-artifact@v4
        with:
          name: RustConnectServer
          path: src/Build/RustConnectServer.exe